name: Benchmark Regression

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r benchmark/requirements.txt

      - name: Build nitr0g3n binary
        run: go build -o bin/nitro ./cmd/nitro

      - name: Run offline benchmark regression
        run: python benchmark/run_benchmarks.py --offline --generate-graphs --output benchmark/results/ci.json

      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-graphs
          path: benchmark/results
          if-no-files-found: ignore
