name: Build Binaries

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Build binary
        shell: bash
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          BINARY_NAME="nitr0g3n_${GOOS}_${GOARCH}"
          if [ "$GOOS" = "windows" ]; then
            BINARY_NAME="${BINARY_NAME}.exe"
          fi
          CGO_ENABLED=0 go build -o "dist/${BINARY_NAME}" .
          echo "artifact_path=dist/${BINARY_NAME}" >> "$GITHUB_OUTPUT"
        id: build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nitr0g3n-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ${{ steps.build.outputs.artifact_path }}
          if-no-files-found: error
