name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Build binary
        id: build
        shell: bash
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          BINARY_NAME="nitr0g3n_${GOOS}_${GOARCH}"
          if [ "$GOOS" = "windows" ]; then
            BINARY_NAME="${BINARY_NAME}.exe"
          fi
          CGO_ENABLED=0 go build -o "dist/${BINARY_NAME}" .
          echo "binary_path=dist/${BINARY_NAME}" >> "$GITHUB_OUTPUT"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.build.outputs.binary_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
